experiment:
  seed: 0
  name: "UNet_experiments_12" #"UNet_baseline_v2" # "training_on_individual_clusters" #"UNet-8x-baseline-T2M", "finetuning"
  save_dir: "/scratch/fquareng/experiments"
  device: "cuda"
  model: UNet8x # UNet8x, UNet8x_BN, UNet8x_DO, UNet8x_DO_BN, UNet8x_Noise

data:
  data_path: "/work/FAC/FGSE/IDYST/tbeucler/downscaling/fquareng/data"
  input_path: "DA/1d-PS-RELHUM_2M-T_2M_cropped_gridded_clustered_threshold_12_blurred"
  target_path: "DA/1d-PS-RELHUM_2M-T_2M_cropped_gridded_clustered_threshold_12"
  dem_path: "dem_squares"
  variable: "T_2M"

training:
  num_epochs: 40
  batch_size: 128
  transform: "theta_e"  # "normalize"
  num_workers: 16  # change to 1 if training on curnagl
  early_stopping: True
  early_stopping_params:
    patience: 10
  criterion: MSELoss
  optimizer: Adam
  optimizer_params:
    lr: 0.0001
    weight_decay: 0.001
  scheduler: ReduceLROnPlateau
  scheduler_params:
    mode: "min"
    factor: 0.5
    patience: 3
    verbose: True

testing:
  criterion: MSELoss
