experiment:
  seed: 0
  name: "finetuning_frozen_v2" # "training_on_individual_clusters" #"UNet-8x-baseline-T2M", "finetuning"
  save_dir: "/scratch/fquareng/experiments"
  device: "cuda"
  model: UNet8x

data:
  data_path: "/work/FAC/FGSE/IDYST/tbeucler/downscaling/fquareng/data"
  input_path: "1h_2D_sel_cropped_gridded_clustered_threshold_blurred/cluster_0"
  target_path: "1h_2D_sel_cropped_gridded_clustered_threshold/cluster_0"
  dem_path: "dem_squares"
  variable: "T_2M"

training:
  num_epochs: 50
  batch_size: 16
  early_stopping: True
  early_stopping_params:
    patience: 10
  snapshot_interval: 5
  criterion: MSELoss
  optimizer: Adam
  optimizer_params:
    lr: 0.00001
  scheduler: ReduceLROnPlateau
  scheduler_params:
    mode: "min"
    factor: 0.5
    patience: 5
    verbose: True

testing:
  criterion: MSELoss
