experiment:
  seed: 0
  name: "UNet_8x_baseline_T2M"
  save_dir: "/Users/fquareng/phd/WeatherAdaptSR/experiments"
  device: "gpu"
  model: UNet8x

data:
  data_path: "/Users/fquareng/data/"
  input_path: "1h_2D_sel_cropped_gridded_clustered_threshold_blurred"
  target_path: "1h_2D_sel_cropped_gridded_clustered_threshold"
  dem_path: "dem_squares"
  variable: "T_2M"

training:
  num_epochs: 50
  batch_size: 16
  patience: 5
  snapshot_interval: 5
  criterion: MSELoss
  optimizer: Adam
  optimizer_params:
    lr: 0.0001
  scheduler: StepLR
  scheduler_params:
    step_size: 10
    gamma: 0.5

testing:
  criterion: MSELoss