experiment:
  name: "cross_val_opt"
  save_dir: "/scratch/fquareng/experiments"
  device: "cuda"
  model: UNet
  # UNet
  # UNet_BN
  # UNet_DO
  # UNet_DO_BN
  # UNet_Noise
  # UNet_Noise_DO_BN
  # UNet_Trainable_Noise

paths:
  local_dir: "/work/FAC/FGSE/IDYST/tbeucler/downscaling/fquareng/WeatherAdaptSR"
  data_path: "/work/FAC/FGSE/IDYST/tbeucler/downscaling/fquareng/data/clusters"

training:
  num_epochs: 50
  batch_size: 16
  use_theta_e: False
  load_data_on_gpu: False
  num_workers: 1  # change to 1 if training on curnagl
  early_stopping: True
  early_stopping_params:
    patience: 10
  criterion: MSELoss
  optimizer: Adam
  # optimizer_params:
  #   lr: 0.0005
  #   weight_decay: 0.0001
  scheduler: ReduceLROnPlateau
  scheduler_params:
    mode: "min"
    factor: 0.5
    patience: 5
    verbose: True

testing:
  criterion: MSELoss

optimization:
  num_epochs: 5  # 0 if not optimizing
  num_trials: 10

domain_specific:
  cluster_0:
    optimizer_params:
      lr: 0.0005
      weight_decay: 0.0001
  cluster_1:
    optimizer_params:
      lr: 0.0005
      weight_decay: 0.0001
  cluster_2:
    optimizer_params:
      lr: 0.0005
      weight_decay: 0.0001
  cluster_3:
    optimizer_params:
      lr: 0.0005
      weight_decay: 0.0001
  cluster_4:
    optimizer_params:
      lr: 0.0005
      weight_decay: 0.0001
  cluster_5:
    optimizer_params:
      lr: 0.0005
      weight_decay: 0.0001
  cluster_6:
    optimizer_params:
      lr: 0.0005
      weight_decay: 0.0001
  cluster_7:
    optimizer_params:
      lr: 0.0005
      weight_decay: 0.0001
  cluster_8:
    optimizer_params:
      lr: 0.0005
      weight_decay: 0.0001
  cluster_9:
    optimizer_params:
      lr: 0.0005
      weight_decay: 0.0001
  cluster_10:
    optimizer_params:
      lr: 0.0005
      weight_decay: 0.0001
  cluster_11:
    optimizer_params:
      lr: 0.0005
      weight_decay: 0.0001