experiment:
  seed: 0
  name: "UNet_mdan" #"UNet_baseline_v2" # "training_on_individual_clusters" #"UNet-8x-baseline-T2M", "finetuning"
  save_dir: "/scratch/fquareng/experiments"
  device: "cpu"
  model: UNet8x_Noise # UNet8x, UNet8x_BN, UNet8x_DO, UNet8x_DO_BN, UNet8x_Noise

data:
  data_path: "/work/FAC/FGSE/IDYST/tbeucler/downscaling/fquareng/data"
  input_path: "DA/8h-PS-RELHUM_2M-T_2M_cropped_gridded_clustered_threshold_blurred"
  target_path: "DA/8h-PS-RELHUM_2M-T_2M_cropped_gridded_clustered_threshold"
  dem_path: "dem_squares"
  variable: "T_2M"

training:
  num_epochs: 100
  batch_size: 16
  num_workers: 1
  early_stopping: True
  early_stopping_params:
    patience: 10
  criterion: MSELoss
  optimizer: Adam
  optimizer_params:
    lr: 0.0005
    weight_decay: 0.0001
  scheduler: ReduceLROnPlateau
  scheduler_params:
    mode: "min"
    factor: 0.5
    patience: 5
    verbose: True
  domain_adaptation: 
    criterion: CrossEntropyLoss
    training_mode: dynamic # maxmin, dynamic
    mu: 0.01
    gamma: 10.0

testing:
  criterion: MSELoss
