experiment:
  seed: 0
  name: "training_on_individual_clusters"
  save_dir: "/scratch/fquareng/experiments"
  device: "gpu"
  model: UNet8x

data:
  data_path: "/work/FAC/FGSE/IDYST/tbeucler/downscaling/fquareng/data/"
  input_path: "1h_2D_sel_cropped_gridded_clustered_threshold_blurred/cluster_1"
  target_path: "1h_2D_sel_cropped_gridded_clustered_threshold/cluster_1"
  dem_path: "dem_squares"
  variable: "T_2M"

training:
  num_epochs: 50
  batch_size: 16
  patience: 10
  snapshot_interval: 5
  criterion: MSELoss
  optimizer: Adam
  optimizer_params:
    lr: 0.0001
  scheduler: StepLR
  scheduler_params:
    step_size: 10
    gamma: 0.5

testing:
  criterion: MSELoss
