experiment:
  seed: 0
  name: "UNet_cross_val" #"UNet_baseline_v2" # "training_on_individual_clusters" #"UNet-8x-baseline-T2M", "finetuning"
  save_dir: "/scratch/fquareng/experiments"
  device: "cuda"
  model: UNet8x
  # UNet8x
  # UNet8x_BN
  # UNet8x_DO
  # UNet8x_DO_BN
  # UNet8x_Noise
  # UNet8x_Noise_DO_BN
  # UNet8x_Noise_Trainable_DO_BN
  # UNet8x_HighRes_Noise_Trainable_DO_BN

data:
  data_path: "/work/FAC/FGSE/IDYST/tbeucler/downscaling/fquareng/data"
  input_path: "DA/1d-PS-RELHUM_2M-T_2M_cropped_gridded_clustered_threshold_12_blurred"
  target_path: "DA/1d-PS-RELHUM_2M-T_2M_cropped_gridded_clustered_threshold_12"
  dem_path: "dem_squares"
  variable: "T_2M"

training:
  num_epochs: 50
  batch_size: 16
  transform: None # None, "theta_e" 
  num_workers: 1  # change to 1 if training on curnagl
  early_stopping: True
  early_stopping_params:
    patience: 10
  criterion: MSELoss
  optimizer: Adam
  # optimizer_params:
  #   lr: 0.0005
  #   weight_decay: 0.0001
  scheduler: ReduceLROnPlateau
  scheduler_params:
    mode: "min"
    factor: 0.5
    patience: 5
    verbose: True

testing:
  criterion: MSELoss

optimization:
  num_epochs: 5

domain_specific:
  cluster_0:
    optimizer_params:
      lr: 0.0005
      weight_decay: 0.0001
  cluster_1:
    optimizer_params:
      lr: 0.0005
      weight_decay: 0.0001
  cluster_2:
    optimizer_params:
      lr: 0.0005
      weight_decay: 0.0001
  cluster_3:
    optimizer_params:
      lr: 0.0005
      weight_decay: 0.0001
  cluster_4:
    optimizer_params:
      lr: 0.0005
      weight_decay: 0.0001
  cluster_5:
    optimizer_params:
      lr: 0.0005
      weight_decay: 0.0001
  cluster_6:
    optimizer_params:
      lr: 0.0005
      weight_decay: 0.0001
  cluster_7:
    optimizer_params:
      lr: 0.0005
      weight_decay: 0.0001
  cluster_8:
    optimizer_params:
      lr: 0.0005
      weight_decay: 0.0001
  cluster_9:
    optimizer_params:
      lr: 0.0005
      weight_decay: 0.0001
  cluster_10:
    optimizer_params:
      lr: 0.0005
      weight_decay: 0.0001
  cluster_11:
    optimizer_params:
      lr: 0.0005
      weight_decay: 0.0001