experiment:
  name: "UNet_8x_baseline"
  save_dir: "/scratch/fquareng/experiments"
  seed: 0

training:
  num_epochs: 50
  log_every_n_steps: 10
  batch_size: 16
  patience: 5
  lr: 0.0001
  device: "cuda"

data:
  variable: "T_2M"
  input_dir: "/work/FAC/FGSE/IDYST/tbeucler/downscaling/fquareng/data/1h_2D_sel_cropped_gridded_clustered_threshold_blurred"
  target_dir: "/work/FAC/FGSE/IDYST/tbeucler/downscaling/fquareng/data/1h_2D_sel_cropped_gridded_clustered_threshold"
  elevation_dir: "/work/FAC/FGSE/IDYST/tbeucler/downscaling/fquareng/data/dem_squares"