experiment:
  name: "homoscedastic_DA_v1" #"single-10x-ssim-mse" # "cross-val-v8"
  save_dir: "/scratch/fquareng/experiments"
  device: "cuda"  # "cuda" or "cpu"
  vars: ["T_2M", "TOT_PREC"]

paths:
  local_dir: "/work/FAC/FGSE/IDYST/tbeucler/downscaling/fquareng/WeatherAdaptSR"
  data_path: "/work/FAC/FGSE/IDYST/tbeucler/downscaling/fquareng/data/clusters_v6"
  elev_path: "/work/FAC/FGSE/IDYST/tbeucler/downscaling/fquareng/data/dem_squares"
  stats_path: "master_pooled_stats.json"
  clusters: [
    "cluster_0",
    "cluster_1",
    "cluster_2",
    "cluster_3",
    "cluster_4",
    #"cluster_5",
    #"cluster_6",
    #"cluster_7",
    # "cluster_8",
    # "cluster_9",
    # "cluster_10",
    # "cluster_11",
  ]
  # single_cluster: "cluster_0"

optimization:
  num_epochs: 10
  num_trials: 10

training:
  init_b_T: 0.5
  init_b_P: 0.5
  augmentation: False
  num_epochs: 100
  batch_size: 32
  use_theta_e: False
  load_data_on_gpu: True
  num_workers: 0  # 0 if on GH200
  early_stopping: True
  early_stopping_params:
    patience: 10
    min_delta: 0.01
  criterion: L1Loss # MSELoss
  optimizer: Adam
  scheduler: ReduceLROnPlateau
  scheduler_params:
    mode: 'min'  # 'min' for MSELoss/L1Loss, 'max' for accuracy
    factor: 0.1
    patience: 5
  mmd:
    lambda_max: 1

testing:
  criterion: L1Loss # MSELoss

domain_specific:
  all_clusters:
    loss_params:
      lr_loss_P: 0.0001
      lr_loss_T: 0.0001
      weight_decay: 0.0
    optimizer_params:
      lr_model: 0.0001
      weight_decay: 1.0e-05
  cluster_0:
    loss_params:
      lr_loss_P: 0.0008309095394437387
      lr_loss_T: 9.524595614347883e-05
      weight_decay: 0.0
    optimizer_params:
      lr_model: 0.0003966922470296711
      weight_decay: 4.858621604740102e-05
  cluster_1:
    loss_params:
      lr_loss_P: 0.0009354355252769969
      lr_loss_T: 0.000423889317595009
      weight_decay: 0.0
    optimizer_params:
      lr_model: 0.0004664887977195625
      weight_decay: 0.009331087453492358
  cluster_10:
    loss_params:
      lr_loss_P: 0.0001
      lr_loss_T: 0.0001
      weight_decay: 0.0
    optimizer_params:
      lr_model: 0.00012393557885107537
      weight_decay: 1.183175858041721e-05
  cluster_11:
    loss_params:
      llr_loss_T: 0.0001
      lr_loss_P: 0.0001
      weight_decay: 0.0
    optimizer_params:
      lr_model: 6.929905784207916e-05
      weight_decay: 2.5955438444608163e-05
  cluster_2:
    loss_params:
      lr_loss_P: 0.00037536781624075526
      lr_loss_T: 0.0001835691725223158
      weight_decay: 0.0
    optimizer_params:
      lr_model: 2.2994874872541756e-05
      weight_decay: 0.007276347058350459
  cluster_3:
    loss_params:
      lr_loss_P: 0.00030792219541516964
      lr_loss_T: 0.0004779216014100517
      weight_decay: 0.0
    optimizer_params:
      lr_model: 8.179128617796567e-05
      weight_decay: 0.0005104192048960632
  cluster_4:
    loss_params:
      lr_loss_P: 0.0006966348125951738
      lr_loss_T: 3.439056500340435e-05
      weight_decay: 0.0
    optimizer_params:
      lr_model: 2.186523867968388e-05
      weight_decay: 0.00024854720309511283
  cluster_5:
    loss_params:
      lr_loss_P: 0.0001
      lr_loss_T: 0.0001
      weight_decay: 0.0
    optimizer_params:
      lr_model: 2.032703875649766e-05
      weight_decay: 3.2284575168535546e-05
  cluster_6:
    loss_params:
      lr_loss_P: 0.0001
      lr_loss_T: 0.0001
      weight_decay: 0.0
    optimizer_params:
      lr_model: 4.951768649864631e-06
      weight_decay: 7.849846187099783e-06
  cluster_7:
    loss_params:
      lr_loss_P: 0.0001
      lr_loss_T: 0.0001
      weight_decay: 0.0
    optimizer_params:
      lr_model: 1.5245527478222927e-05
      weight_decay: 0.00017318314906004183
  cluster_8:
    loss_params:
      lr_loss_P: 0.0001
      lr_loss_T: 0.0001
      weight_decay: 0.0
    optimizer_params:
      lr_model: 3.60232484808421e-06
      weight_decay: 4.580783173280096e-06
  cluster_9:
    loss_params:
      lr_loss_P: 0.0001
      lr_loss_T: 0.0001
      weight_decay: 0.0
    optimizer_params:
      lr_model: 4.580079928910211e-06
      weight_decay: 0.00012448253031874595